#include "mblet/jsonator.h"
#include <vector>

int main(int argc, char* argv[]) {
    if (argc != 2) {
        std::cerr << "Usage: " << argv[0] << " JSON_FILE" << std::endl;
        return 1;
    }
    mblet::Jsonator jsonator;
    jsonator.parseFile(argv[1]);
    // mblet::Jsonator::Map map;
    // char* test = (char*)"test";
    // map["key"] = "test";
    // map["type"] = "test";
    // map["array"][0][0][0][0][0][0][0][0][0][0]["test"] = test;
    // jsonator.getMap()["3"] = map;
    // jsonator["object"]["2"];
    std::string strKey2 = jsonator["key"];
    const double& dd = jsonator["number"];
    mblet::Jsonator::Map strKey = jsonator["object"];
    const mblet::Jsonator::Map* ptrMap = &jsonator["key"];
    const char* nu = "number";
    double testd = jsonator[nu].get<double>();
    std::cout << ptrMap->get<std::string>() << std::endl;
    std::cout << jsonator["number"].get<int>() << std::endl;
    std::cout << strKey2 << std::endl;
    std::cout << testd << std::endl;
    std::cout << dd << std::endl;
    std::cout << strKey["null"] << std::endl;
    // std::cout << jsonator.dump(2) << std::endl;
    std::cout << jsonator.dump() << std::endl;
    std::string str = jsonator.dump(0);
    jsonator.parseString(str);
    mblet::Jsonator::Map map(jsonator.getMap());
    map["object"]["1"] = "test";
    map["array"][1][1] = 42;
    map[nu] = 32;
    map[nu + 1] = true;
    bool boolean = map[nu + 1];
    map["array\\"][1][1] = 42;
    const char ttt[4] = "key";
    map.erase(ttt);
    mblet::Jsonator::Map testai;
    testai.push_back(0);
    testai.push_back("1");
    testai.push_back(2);
    testai.push_back(3);
    std::cout << testai << std::endl;
    testai.push_front(4);
    std::cout << testai << std::endl;
    std::cout << testai[3] << std::endl;
    testai.erase(3);
    testai.erase(3);
    std::cout << testai << std::endl;
    testai.pop_front();
    testai.pop_front();
    testai.pop_back();
    std::cout << testai << std::endl;
    testai[0];
    std::cout << testai << std::endl;
    mblet::Jsonator::Map testas;
    testas.push_front(42);
    // testas.erase(0)[0];
    map["array"][2] = testai;
    map["array"][3] = testas;
    std::cout << map.at("object").getKey() << std::endl;
    std::cout << map.at("object").isObject() << std::endl;
    std::cout << map.at("object").isArray() << std::endl;
    std::cout << map.at("object").isString() << std::endl;
    std::cout << map.at("array").at(0) << std::endl;
    std::cout << map["array"] << std::endl;
    std::cout << boolean << boolean << std::endl;
    // std::cout << jsonator["0"]["0"] << std::endl;
    // std::cout << jsonator["0"]["0"]["0"] << std::endl;
    // std::cout << jsonator["0"]["0"]["0"]["0"] << std::endl;
    // std::cout << jsonator["0"]["0"]["0"]["0"]["0"] << std::endl;
    // std::cout << jsonator["0"]["0"]["0"]["0"]["0"]["0"] << std::endl;
    // std::cout << jsonator["0"]["0"]["0"]["0"]["0"]["0"]["0"] << std::endl;
    // std::cout << jsonator["0"]["0"]["0"]["0"]["0"]["0"]["0"]["0"].dump(4) << std::endl;
    // std::cout << jsonator["0"]["0"]["0"]["0"]["0"]["0"]["0"]["0"]["0"].dump(4) << std::endl;
    // std::cout << map.dump(2) << std::endl;
    // unsigned int u = 0;
    // mblet::Jsonator::Map map2;
    // map2[0][1].erase(u);
    // map[""].erase(0);
    // map[""]["array"][1][0][0].erase(u)[u] = 24;
    map["array"].erase(0).push_front(24);
    map["array\\"][0].newNull();
    std::cout << map.dump(2) << std::endl;
    return 0;
}