// Generated by amalgamate.py
#ifndef _AMALGAMATE_GUARD__SINGLE_INCLUDE_MBLET_JSONATOR_H_
#define _AMALGAMATE_GUARD__SINGLE_INCLUDE_MBLET_JSONATOR_H_

/**
 * jsonator.h
 *
 * Licensed under the MIT License <http://opensource.org/licenses/MIT>.
 * Copyright (c) 2022-2023 BLET Mickaël.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef _MBLET_JSONATOR_H_
#define _MBLET_JSONATOR_H_

#include <deque>     // std::deque
#include <exception> // std::exception
#include <list>      // std::list
#include <map>       // std::map
#include <queue>     // std::queue
#include <set>       // std::set
#include <sstream>   // std::istream, std::ostream, std:ostringstream
#include <stack>     // std::stack
#include <string>    // std::string
#include <vector>    // std::vector

namespace mblet {

/**
 * @brief Parse and create a json object
 */
class Jsonator {
  public:
    typedef std::vector<Jsonator>::const_iterator array_const_iterator;
    typedef std::vector<Jsonator>::iterator array_iterator;
    typedef std::map<std::string, Jsonator>::const_iterator object_const_iterator;
    typedef std::map<std::string, Jsonator>::iterator object_iterator;

    /**
     * @brief Parse exception from Exception
     */
    class ParseException : public std::exception {
      public:
        ParseException(const std::string& filename, const std::string& message) :
            std::exception(),
            _filename(filename),
            _message(message),
            _line(0),
            _column(0) {
            std::ostringstream oss("");
            oss << "Parse ";
            if (!filename.empty()) {
                oss << filename << ':';
            }
            oss << " (" << message << ").";
            _what = oss.str();
        };
        ParseException(const std::string& filename, std::size_t line, std::size_t column, const std::string& message) :
            std::exception(),
            _filename(filename),
            _message(message),
            _line(line),
            _column(column) {
            std::ostringstream oss("");
            oss << "Parse at ";
            if (!filename.empty()) {
                oss << filename << ':';
            }
            oss << line << ':' << column << " (" << message << ").";
            _what = oss.str();
        };
        virtual ~ParseException() throw() {}
        const char* what() const throw() {
            return _what.c_str();
        }
        const std::string& filename() const throw() {
            return _filename;
        }
        const std::string& message() const throw() {
            return _message;
        }
        const std::size_t& line() const throw() {
            return _line;
        }
        const std::size_t& column() const throw() {
            return _column;
        }

      protected:
        std::string _what;
        std::string _filename;
        std::string _message;
        std::size_t _line;
        std::size_t _column;
    };

    /**
     * @brief Access exception from std::exception
     */
    class AccessException : public std::exception {
      public:
        AccessException(const Jsonator& json, const char* message) :
            std::exception(),
            _message(message),
            _json(json) {
            std::ostringstream oss("");
            if (json._parent) {
                jsonToPath(oss, json);
                oss << ' ';
            }
            oss << message << " (is " << getStrFromType(json._type) << ")" << '.';
            _what = oss.str();
        }
        virtual ~AccessException() throw() {}
        const char* what() const throw() {
            return _what.c_str();
        }
        const std::string& message() const throw() {
            return _message;
        }
        const Jsonator& json() const throw() {
            return _json;
        }

      protected:
        static void jsonToPath(std::ostream& oss, const Jsonator& json) {
            std::stack<const Jsonator*> jsons;
            const Jsonator* pJson = json._parent;
            while (pJson != NULL) {
                jsons.push(pJson);
                pJson = pJson->_parent;
            }
            while (!jsons.empty()) {
                if (jsons.top()->_parent) {
                    if (jsons.top()->_parent->isObject()) {
                        oss << "[\"" << jsons.top()->_objectKey << "\"]";
                    }
                    else if (jsons.top()->_parent && jsons.top()->_parent->isArray()) {
                        oss << '[' << jsons.top()->_arrayIndex << ']';
                    }
                }
                jsons.pop();
            }
            if (json._parent && json._parent->isObject()) {
                oss << "[\"" << json._objectKey << "\"]";
            }
            if (json._parent && json._parent->isArray()) {
                oss << '[' << json._arrayIndex << ']';
            }
        }

        std::string _what;
        std::string _message;
        const Jsonator& _json;
    };

    /**
     * @brief Child exception from AccessException
     */
    class ChildException : public AccessException {
      public:
        ChildException(const Jsonator& json, unsigned long index) :
            AccessException(json, "out of range"),
            _index(index) {
            std::ostringstream oss("");
            if (json._parent) {
                jsonToPath(oss, json);
                oss << ' ';
            }
            oss << _message << " '" << index << "'.";
            _what = oss.str();
        }
        ChildException(const Jsonator& json, const std::string& child) :
            AccessException(json, "has not a child"),
            _child(child) {
            std::ostringstream oss("");
            if (json._parent) {
                jsonToPath(oss, json);
                oss << ' ';
            }
            oss << _message << " '" << child << "'.";
            _what = oss.str();
        }
        virtual ~ChildException() throw() {}
        const std::string& child() const throw() {
            return _child;
        }
        const unsigned long& index() const throw() {
            return _index;
        }

      protected:
        unsigned long _index;
        std::string _child;
    };

    /**
     * @brief type of jsonator
     */
    enum Type {
        NONE = 0,
        OBJECT,
        ARRAY,
        STRING,
        NUMBER,
        BOOLEAN
    };

    /**
     * @brief Get the Str From Type
     *
     * @param type
     * @return const char*
     */
    static const char* getStrFromType(const Type& type) {
        const char* ret = NULL;
        switch (type) {
            case NONE:
                ret = "NONE";
                break;
            case OBJECT:
                ret = "OBJECT";
                break;
            case ARRAY:
                ret = "ARRAY";
                break;
            case STRING:
                ret = "STRING";
                break;
            case NUMBER:
                ret = "NUMBER";
                break;
            case BOOLEAN:
                ret = "BOOLEAN";
                break;
        }
        return ret;
    }

    /**
     * @brief override operator stream for print value
     *
     * @param os
     * @param json
     * @return std::ostream&
     */
    friend std::ostream& operator<<(std::ostream& os, const Jsonator& json) {
        switch (json.getType()) {
            case OBJECT:
            case ARRAY:
                os << json.dump();
                break;
            case NONE:
                os << "null";
                break;
            case STRING:
                os << json.getString();
                break;
            case NUMBER:
                os << json.getNumber();
                break;
            case BOOLEAN:
                os << json.getBoolean();
                break;
        }
        return os;
    }

    /**
     * @brief Construct the Jsonator object
     */
    Jsonator();

    /**
     * @brief Construct a new Jsonator object
     *
     * @param rhs
     */
    Jsonator(const Jsonator& rhs);

    /**
     * @brief Destroy the Jsonator object
     */
    ~Jsonator();

    /**
     * @brief copy json
     *
     * @param json
     */
    void operator=(const Jsonator& json);

    /**
     * @brief set value from str
     *
     * @param value : new value
     * @throw AccessException if type is not none or not a string
     */
    void operator=(const std::string& value) {
        newString(value);
    }

    /**
     * @brief set value from str
     *
     * @param value : new value
     * @throw AccessException if type is not none or not a string
     */
    void operator=(const char* value) {
        newString(value);
    }

    /**
     * @brief set value from str
     *
     * @param value : new value
     * @throw AccessException if type is not none or not a string
     */
    template<std::size_t Size>
    void operator=(const char (&value)[Size]) {
        newString(std::string(value));
    }

    /**
     * @brief set value from bool
     *
     * @param value : new value
     * @throw AccessException if type is not none or not a boolean
     */
    void operator=(const bool& value) {
        newBoolean(value);
    }

    /**
     * @brief set value from deque
     *
     * @tparam T
     * @param value
     * @throw AccessException if type is not none or not a array
     */
    template<typename T>
    void operator=(const std::deque<T>& value) {
        typename std::deque<T>::const_iterator it;
        for (it = value.begin(); it != value.end(); ++it) {
            push_back(*it);
        }
    }

    /**
     * @brief set value from list
     *
     * @tparam T
     * @param value
     * @throw AccessException if type is not none or not a array
     */
    template<typename T>
    void operator=(const std::list<T>& value) {
        typename std::list<T>::const_iterator it;
        for (it = value.begin(); it != value.end(); ++it) {
            push_back(*it);
        }
    }

    /**
     * @brief set value from map
     *
     * @tparam T key
     * @tparam U value
     * @param value
     * @throw AccessException if type is not none or not a array
     */
    template<typename T, typename U>
    void operator=(const std::map<T, U>& value) {
        typename std::map<T, U>::const_iterator it;
        for (it = value.begin(); it != value.end(); ++it) {
            operator[](it->first) = it->second;
        }
    }

    /**
     * @brief set value from queue
     *
     * @tparam T
     * @param value
     * @throw AccessException if type is not none or not a array
     */
    template<typename T>
    void operator=(const std::queue<T>& value) {
        std::queue<T> copy = value;
        while (!copy.empty()) {
            push_back(copy.front());
            copy.pop();
        }
    }

    /**
     * @brief set value from set
     *
     * @tparam T
     * @param value
     * @throw AccessException if type is not none or not a array
     */
    template<typename T>
    void operator=(const std::set<T>& value) {
        typename std::set<T>::const_iterator it;
        for (it = value.begin(); it != value.end(); ++it) {
            push_back(*it);
        }
    }

    /**
     * @brief set value from stack
     *
     * @tparam T
     * @param value
     * @throw AccessException if type is not none or not a array
     */
    template<typename T>
    void operator=(const std::stack<T>& value) {
        std::stack<T> copy = value;
        while (!copy.empty()) {
            push_back(copy.top());
            copy.pop();
        }
    }

    /**
     * @brief set value from vector
     *
     * @tparam T
     * @param value
     * @throw AccessException if type is not none or not a array
     */
    template<typename T>
    void operator=(const std::vector<T>& value) {
        typename std::vector<T>::const_iterator it;
        for (it = value.begin(); it != value.end(); ++it) {
            push_back(*it);
        }
    }

    /**
     * @brief set value from number
     *
     * @tparam T
     * @param value
     * @throw AccessException if type is not none or not a number
     */
    template<typename T>
    void operator=(const T& value) {
        newNumber(value);
    }

    /**
     * @brief find by key
     *
     * @param key
     * @return iterator
     * @throw AccessException if type is not a object
     */
    object_iterator find(const std::string& key) {
        if (_type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        return _object.find(key);
    }

    /**
     * @brief find by key
     *
     * @param key
     * @return const_iterator
     * @throw AccessException if type is not a object
     */
    object_const_iterator find(const std::string& key) const {
        if (_type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        return _object.find(key);
    }

    /**
     * @brief find by key
     *
     * @param key
     * @return iterator
     * @throw AccessException if type is not a object
     */
    object_iterator find(const char* key) {
        return find(std::string(key));
    }

    /**
     * @brief find by key
     *
     * @param key
     * @return const_iterator
     * @throw AccessException if type is not a object
     */
    object_const_iterator find(const char* key) const {
        return find(std::string(key));
    }

    /**
     * @brief find by key
     *
     * @tparam Size
     * @return iterator
     * @throw AccessException if type is not a object
     */
    template<std::size_t Size>
    object_iterator find(const char (&key)[Size]) {
        return find(std::string(key));
    }

    /**
     * @brief find by key
     *
     * @tparam Size
     * @return const_iterator
     * @throw AccessException if type is not a object
     */
    template<std::size_t Size>
    object_const_iterator find(const char (&key)[Size]) const {
        return find(std::string(key));
    }

    /**
     * @brief find by index
     *
     * @tparam T
     * @param index
     * @return iterator
     * @throw AccessException if type is not a array
     */
    template<typename T>
    array_iterator find(const T& index) {
        if (_type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        if (static_cast<std::size_t>(index) < _array.size()) {
            return _array.begin() + index;
        }
        else {
            return _array.end();
        }
    }

    /**
     * @brief find by index
     *
     * @tparam T
     * @param index
     * @return const_iterator
     * @throw AccessException if type is not a array
     */
    template<typename T>
    array_const_iterator find(const T& index) const {
        if (_type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        if (static_cast<std::size_t>(index) < _array.size()) {
            return _array.begin() + index;
        }
        else {
            return _array.end();
        }
    }

    /**
     * @brief get json from @p key
     *
     * @param key
     * @return Jsonator& data associated with the key or if the key does not exist,
     * a json object with that key is created using default values, which is then returned
     * @throw AccessException if type is not a null and not a object
     */
    Jsonator& operator[](const std::string& key) {
        if (_type == NONE) {
            _type = OBJECT;
        }
        object_iterator it = find(key);
        if (it != _object.end()) {
            return it->second;
        }
        return _object.insert(std::pair<std::string, Jsonator>(key, Jsonator(this, key))).first->second;
    }

    /**
     * @brief get const json from @p key
     *
     * @param key
     * @return const Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    const Jsonator& operator[](const std::string& key) const {
        object_const_iterator it = find(key);
        if (it != _object.end()) {
            return it->second;
        }
        throw ChildException(*this, key);
    }

    /**
     * @brief get json from @p key
     *
     * @param key
     * @return Jsonator& data associated with the key or if the key does not exist,
     * a json object with that key is created using default values, which is then returned
     * @throw AccessException if type is not a null and not a object
     */
    Jsonator& operator[](const char* key) {
        return operator[](std::string(key));
    }

    /**
     * @brief get const json from @p key
     *
     * @param key
     * @return const Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    const Jsonator& operator[](const char* key) const {
        return operator[](std::string(key));
    }

    /**
     * @brief get json from @p key
     *
     * @param key
     * @return Jsonator& data associated with the key or if the key does not exist,
     * a json object with that key is created using default values, which is then returned
     * @throw AccessException if type is not a null and not a object
     */
    template<std::size_t Size>
    Jsonator& operator[](const char (&key)[Size]) {
        return operator[](std::string(key));
    }

    /**
     * @brief get const json from @p key
     *
     * @param key
     * @return const Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    template<std::size_t Size>
    const Jsonator& operator[](const char (&key)[Size]) const {
        return operator[](std::string(key));
    }

    /**
     * @brief get json from @p index if the lowers indexies not exists create of null object
     *
     * @param index
     * @return Jsonator& data associated with the index or if the index does not exist,
     * a json object with that index is created using default values, which is then returned
     * @throw AccessException if type is not a null and not a array
     */
    template<typename T>
    Jsonator& operator[](const T& index) {
        if (_type == NONE) {
            _type = ARRAY;
        }
        array_iterator it = find(index);
        if (it != _array.end()) {
            return *it;
        }
        while (_array.size() < static_cast<std::size_t>(index)) {
            _array.push_back(Jsonator(this, _array.size()));
        }
        _array.push_back(Jsonator(this, index));
        return _array.back();
    }

    /**
     * @brief get const json from @p index
     *
     * @param index
     * @return const Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    template<typename T>
    const Jsonator& operator[](const T& index) const {
        array_const_iterator it = find(index);
        if (it != _array.end()) {
            return *it;
        }
        throw ChildException(*this, index);
    }

    /**
     * @brief get json from @p key
     *
     * @param key
     * @return Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    Jsonator& at(const std::string& key) {
        object_iterator it = find(key);
        if (it != _object.end()) {
            return it->second;
        }
        throw ChildException(*this, key);
    }

    /**
     * @brief get const json from @p key
     *
     * @param key
     * @return const Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    const Jsonator& at(const std::string& key) const {
        object_const_iterator it = find(key);
        if (it != _object.end()) {
            return it->second;
        }
        throw ChildException(*this, key);
    }

    /**
     * @brief get json from @p key
     *
     * @param key
     * @return Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    Jsonator& at(const char* key) {
        return at(std::string(key));
    }

    /**
     * @brief get const json from @p key
     *
     * @param key
     * @return const Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    const Jsonator& at(const char* key) const {
        return at(std::string(key));
    }

    /**
     * @brief get json from @p key
     *
     * @param key
     * @return Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    template<std::size_t Size>
    Jsonator& at(const char (&key)[Size]) {
        return at(std::string(key));
    }

    /**
     * @brief get const json from @p key
     *
     * @param key
     * @return const Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    template<std::size_t Size>
    const Jsonator& at(const char (&key)[Size]) const {
        return at(std::string(key));
    }

    /**
     * @brief get json from @p index
     *
     * @param index
     * @return Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    template<typename T>
    Jsonator& at(const T& index) {
        array_iterator it = find(index);
        if (it != _array.end()) {
            return *it;
        }
        throw ChildException(*this, index);
    }

    /**
     * @brief get const json from @p index
     *
     * @param index
     * @return const Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    template<typename T>
    const Jsonator& at(const T& index) const {
        array_const_iterator it = find(index);
        if (it != _array.end()) {
            return *it;
        }
        throw ChildException(*this, index);
    }

    /**
     * @brief Check if json object is empty
     *
     * @return true if is empty
     */
    bool empty() const {
        if (_type == ARRAY) {
            return _array.empty();
        }
        else if (_type == OBJECT) {
            return _object.empty();
        }
        else {
            return true;
        }
    }

    /**
     * @brief get the const iterator of begin object
     *
     * @return object_const_iterator
     */
    object_const_iterator object_begin() const {
        if (_type != NONE && _type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        return _object.begin();
    }

    /**
     * @brief get the iterator of begin object
     *
     * @return object_const_iterator
     */
    object_iterator object_begin() {
        if (_type != NONE && _type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        return _object.begin();
    }

    /**
     * @brief get the const iterator of begin array
     *
     * @return object_const_iterator
     */
    array_const_iterator array_begin() const {
        if (_type != NONE && _type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        return _array.begin();
    }

    /**
     * @brief get the iterator of begin array
     *
     * @return object_const_iterator
     */
    array_iterator array_begin() {
        if (_type != NONE && _type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        return _array.begin();
    }

    /**
     * @brief get the const iterator of end object
     *
     * @return object_const_iterator
     */
    object_const_iterator object_end() const {
        if (_type != NONE && _type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        return _object.end();
    }

    /**
     * @brief get the iterator of end object
     *
     * @return object_const_iterator
     */
    object_iterator object_end() {
        if (_type != NONE && _type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        return _object.end();
    }

    /**
     * @brief get the const iterator of end array
     *
     * @return object_const_iterator
     */
    array_const_iterator array_end() const {
        if (_type != NONE && _type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        return _array.end();
    }

    /**
     * @brief get the iterator of end array
     *
     * @return object_const_iterator
     */
    array_iterator array_end() {
        if (_type != NONE && _type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        return _array.end();
    }

    /**
     * @brief get the size of object or array
     *
     * @return std::size_t
     */
    std::size_t size() const {
        if (_type == ARRAY) {
            return _array.size();
        }
        else if (_type == OBJECT) {
            return _object.size();
        }
        return 0;
    }

    /**
     * @brief get first json element
     *
     * @return Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    Jsonator& front() {
        return at(0);
    }

    /**
     * @brief get first json element
     *
     * @return Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    const Jsonator& front() const {
        return at(0);
    }

    /**
     * @brief get last json element
     * create then if not exist
     *
     * @return Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    Jsonator& back() {
        if (_array.size() == 0) {
            return at(0);
        }
        else {
            return at(_array.size() - 1);
        }
    }

    /**
     * @brief get last json element
     *
     * @return Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    const Jsonator& back() const {
        return at(_array.size() - 1);
    }

    /**
     * @brief insert @p value by @p key
     *
     * @tparam T
     * @param key
     * @param value
     * @return Jsonator&
     * @throw AccessException if type is not a null and not a object
     */
    template<typename T>
    Jsonator& insert(const std::string& key, const T& value) {
        Jsonator& json = operator[](key);
        json = value;
        return json;
    }

    /**
     * @brief insert @p value by @p index
     *
     * @tparam T
     * @param index
     * @param value
     * @return Jsonator&
     * @throw AccessException if type is not a null and not a array
     */
    template<typename T>
    Jsonator& insert(const unsigned long& index, const T& value) {
        Jsonator newValue(this, index);
        newValue = value;
        // move elements
        for (std::size_t i = _array.size(); i > static_cast<std::size_t>(index); --i) {
            Jsonator& n = operator[](i);
            Jsonator& e = _array[i - 1];
            e._arrayIndex = i;
            n._replace(e);
        }
        operator[](index)._replace(newValue);
        return *this;
    }

    /**
     * @brief add @p value at front
     *
     * @tparam T
     * @param value
     * @return Jsonator&
     * @throw AccessException if type is not a null and not a array
     */
    template<typename T>
    Jsonator& push_front(const T& value) {
        Jsonator newValue(this, 0);
        newValue = value;
        // move elements
        for (std::size_t i = _array.size(); i > 0; --i) {
            Jsonator& n = operator[](i);
            Jsonator& e = _array[i - 1];
            e._arrayIndex = i;
            n._replace(e);
        }
        operator[](0)._replace(newValue);
        return *this;
    }

    /**
     * @brief add @p value at back
     *
     * @tparam T
     * @param value
     * @return Jsonator&
     * @throw AccessException if type is not a null and not a array
     */
    template<typename T>
    Jsonator& push_back(const T& value) {
        operator[](_array.size()) = value;
        return *this;
    }

    /**
     * @brief remove first element
     *
     * @return Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    Jsonator& pop_front() {
        erase(0);
        return *this;
    }

    /**
     * @brief remove last element
     *
     * @return Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    Jsonator& pop_back() {
        erase(_array.size() - 1);
        return *this;
    }

    /**
     * @brief create object
     * @throw AccessException if type is not a null and not a object
     */
    void newObject() {
        if (_type != NONE && _type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        _type = OBJECT;
    }

    /**
     * @brief create array
     * @throw AccessException if type is not a null and not a array
     */
    void newArray() {
        if (_type != NONE && _type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        _type = ARRAY;
    }

    /**
     * @brief create string from @p value
     *
     * @tparam T type of value
     * @param value
     * @throw AccessException if type is not a null and not a string
     */
    template<typename T>
    void newString(const T& value) {
        if (_type != NONE && _type != STRING) {
            throw AccessException(*this, "is not a string");
        }
        std::ostringstream oss("");
        oss << value;
        _string = oss.str();
        _type = STRING;
    }

    /**
     * @brief create number from @p value
     *
     * @tparam T type of value
     * @param value
     * @throw AccessException if type is not a null and not a number
     */
    template<typename T>
    void newNumber(const T& value) {
        if (_type != NONE && _type != NUMBER) {
            throw AccessException(*this, "is not a number");
        }
        _number = value;
        _type = NUMBER;
    }

    /**
     * @brief create bool from @p value
     *
     * @tparam T type of value
     * @param value
     * @throw AccessException if type is not a null and not a boolean
     */
    template<typename T>
    void newBoolean(const T& value) {
        if (_type != NONE && _type != BOOLEAN) {
            throw AccessException(*this, "is not a boolean");
        }
        _boolean = value;
        _type = BOOLEAN;
    }

    /**
     * @brief create null
     * @throw AccessException if type is not a null
     */
    void newNull() {
        if (_type != NONE) {
            throw AccessException(*this, "is not a null");
        }
        _type = NONE;
    }

    /**
     * @brief check if type of jsonator is null
     *
     * @return true if type is null else false
     */
    bool isNull() const {
        return _type == NONE;
    }

    /**
     * @brief check if type of jsonator is a object
     *
     * @return true if type is a object else false
     */
    bool isObject() const {
        return _type == OBJECT;
    }

    /**
     * @brief check if type of jsonator is a array
     *
     * @return true if type is a array else false
     */
    bool isArray() const {
        return _type == ARRAY;
    }

    /**
     * @brief check if type of jsonator is a string
     *
     * @return true if type is a string else false
     */
    bool isString() const {
        return _type == STRING;
    }

    /**
     * @brief check if type of jsonator is a number
     *
     * @return true if type is a number else false
     */
    bool isNumber() const {
        return _type == NUMBER;
    }

    /**
     * @brief check if type of jsonator is a boolean
     *
     * @return true if type is a boolean else false
     */
    bool isBoolean() const {
        return _type == BOOLEAN;
    }

    /**
     * @brief check if object contains a @p key
     *
     * @param key
     * @return true if object has key else false
     * @throw AccessException if type is not a object
     */
    bool contains(const std::string& key) const {
        if (_type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        return _object.find(key) != _object.end();
    }

    /**
     * @brief check if object contains a @p key
     *
     * @param key
     * @return true if object has key else false
     * @throw AccessException if type is not a object
     */
    bool contains(const char* key) const {
        return contains(std::string(key));
    }

    /**
     * @brief check if object contains a @p key
     *
     * @param key
     * @return true if object has key else false
     * @throw AccessException if type is not a object
     */
    template<std::size_t Size>
    bool contains(const char (&key)[Size]) const {
        return contains(std::string(key));
    }

    /**
     * @brief check if array contains a @p index
     *
     * @param index
     * @return true if array has index else false
     * @throw AccessException if type is not a array
     */
    template<typename T>
    bool contains(const T& index) const {
        if (_type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        return static_cast<std::size_t>(index) < _array.size();
    }

    /**
     * @brief serialize jsonator to string
     *
     * @param indent
     * @param indentCharacter
     * @return std::string
     */
    std::string dump(std::size_t indent = 0, char indentCharacter = ' ') const;

    /**
     * @brief remove the @p key
     *
     * @param key
     * @return Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    Jsonator& erase(const std::string& key) {
        if (_type != OBJECT) {
            throw AccessException(*this, "is not a object");
        }
        object_iterator it = find(key);
        if (it != _object.end()) {
            _object.erase(key);
            if (_object.empty()) {
                _type = NONE;
            }
        }
        else {
            throw ChildException(*this, key);
        }
        return *this;
    }

    /**
     * @brief remove the @p key
     *
     * @param key
     * @return Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    Jsonator& erase(const char* key) {
        return erase(std::string(key));
    }

    /**
     * @brief remove the @p key
     *
     * @param key
     * @return Jsonator&
     * @throw AccessException if type is not a object
     * @throw ChildException if key is not exists
     */
    template<std::size_t Size>
    Jsonator& erase(const char (&key)[Size]) {
        return erase(std::string(key));
    }

    /**
     * @brief remove the @p index
     *
     * @param index
     * @return Jsonator&
     * @throw AccessException if type is not a array
     * @throw ChildException if index is not exists
     */
    template<typename T>
    Jsonator& erase(const T& index) {
        if (_type != ARRAY) {
            throw AccessException(*this, "is not a array");
        }
        array_iterator it = find(index);
        if (it != _array.end()) {
            // move elements
            for (std::size_t i = index; i < _array.size() - 1; ++i) {
                Jsonator& e = at(i + 1);
                e._arrayIndex = i;
                operator[](i)._replace(e);
            }
            _array.erase(_array.begin() + (_array.size() - 1));
            if (_array.empty()) {
                _type = NONE;
            }
        }
        else {
            throw ChildException(*this, index);
        }
        return *this;
    }

    /**
     * @brief clear and set at none type
     *
     * @return Jsonator&
     */
    Jsonator& clear() {
        _object.clear();
        _array.clear();
        _string = "";
        _number = 0;
        _boolean = false;
        _type = NONE;
        _filename = "";
        return *this;
    }

    /**
     * @brief get the parent json object
     *
     * @return const Jsonator* parent else NULL
     */
    const Jsonator* getParent() const {
        return _parent;
    }

    const std::size_t& getIndex() const {
        return _arrayIndex;
    }

    /**
     * @brief get the key of json object
     *
     * @return const std::string&
     */
    const std::string& getKey() const {
        return _objectKey;
    }

    /**
     * @brief get the string of json object
     *
     * @return const std::string&
     * @throw AccessException if json type is not a string
     */
    const std::string& getString() const {
        if (_type != STRING) {
            throw AccessException(*this, "is not a string");
        }
        return _string;
    }

    /**
     * @brief get the number of json object
     *
     * @return const double&
     * @throw AccessException if json type is not a number
     */
    const double& getNumber() const {
        if (_type != NUMBER) {
            throw AccessException(*this, "is not a number");
        }
        return _number;
    }

    /**
     * @brief get the boolean of json object
     *
     * @return const bool&
     * @throw AccessException if json type is not a boolean
     */
    const bool& getBoolean() const {
        if (_type != BOOLEAN) {
            throw AccessException(*this, "is not a boolean");
        }
        return _boolean;
    }

    /**
     * @brief Get the Type object
     *
     * @return const Type&
     */
    const Type& getType() const {
        return _type;
    }

    /**
     * @brief get the @c T of json object
     *
     * @tparam T
     * @return T
     */
    template<typename T>
    T get() const {
        return *this;
    }

    /**
     * @brief get the @p T of json object
     *
     * @tparam T
     * @param ret
     */
    template<typename T>
    void get(T& ret) const {
        ret = get<T>();
    }

    /**
     * @brief string construct
     *
     * @return const std::string&
     * @throw AccessException if json type is not a string
     */
    operator const std::string&() const {
        return getString();
    }

    /**
     * @brief string construct
     *
     * @return const char*
     * @throw AccessException if json type is not a string
     */
    operator const char*() const {
        return getString().c_str();
    }

    /**
     * @brief bool construct
     *
     * @return const bool&
     * @throw AccessException if json type is not a boolean
     */
    operator const bool&() const {
        return getBoolean();
    }

    /**
     * @brief get json to deque
     *
     * @tparam T
     */
    template<typename T>
    operator std::deque<T>() const {
        std::deque<T> ret;
        if (_type == ARRAY) {
            for (std::size_t i = 0; i < _array.size(); ++i) {
                ret.push_back(_array[i]);
            }
        }
        else if (_type == OBJECT) {
            for (std::map<std::string, Jsonator>::const_iterator it = _object.begin(); it != _object.end(); ++it) {
                ret.push_back(it->second);
            }
        }
        return ret;
    }

    /**
     * @brief get json to list
     *
     * @tparam T
     */
    template<typename T>
    operator std::list<T>() const {
        std::list<T> ret;
        if (_type == ARRAY) {
            for (std::size_t i = 0; i < _array.size(); ++i) {
                ret.push_back(_array[i]);
            }
        }
        else if (_type == OBJECT) {
            for (std::map<std::string, Jsonator>::const_iterator it = _object.begin(); it != _object.end(); ++it) {
                ret.push_back(it->second);
            }
        }
        return ret;
    }

    /**
     * @brief get json to map
     *
     * @tparam T
     * @return std::map<std::string, T>
     */
    template<typename T>
    operator std::map<std::string, T>() const {
        std::map<std::string, T> ret;
        for (std::map<std::string, Jsonator>::const_iterator it = _object.begin(); it != _object.end(); ++it) {
            ret.insert(std::pair<std::string, T>(it->first, it->second));
        }
        return ret;
    }

    /**
     * @brief get json to map
     *
     * @tparam T key
     * @tparam U value
     */
    template<typename T, typename U>
    operator std::map<T, U>() const {
        std::map<T, U> ret;
        for (std::size_t i = 0; i < _array.size(); ++i) {
            ret.insert(std::pair<T, U>(i, _array[i]));
        }
        return ret;
    }

    /**
     * @brief get json to queue
     *
     * @tparam T
     */
    template<typename T>
    operator std::queue<T>() const {
        std::queue<T> ret;
        if (_type == ARRAY) {
            for (std::size_t i = 0; i < _array.size(); ++i) {
                ret.push(_array[i]);
            }
        }
        else if (_type == OBJECT) {
            for (std::map<std::string, Jsonator>::const_iterator it = _object.begin(); it != _object.end(); ++it) {
                ret.push(it->second);
            }
        }
        return ret;
    }

    /**
     * @brief get json to set
     *
     * @tparam T
     */
    template<typename T>
    operator std::set<T>() const {
        std::set<T> ret;
        if (_type == ARRAY) {
            for (std::size_t i = 0; i < _array.size(); ++i) {
                ret.insert(_array[i]);
            }
        }
        else if (_type == OBJECT) {
            for (std::map<std::string, Jsonator>::const_iterator it = _object.begin(); it != _object.end(); ++it) {
                ret.insert(it->second);
            }
        }
        return ret;
    }

    /**
     * @brief get json to stack
     *
     * @tparam T
     */
    template<typename T>
    operator std::stack<T>() const {
        std::stack<T> ret;
        if (_type == ARRAY) {
            for (std::size_t i = 0; i < _array.size(); ++i) {
                ret.push(_array[i]);
            }
        }
        else if (_type == OBJECT) {
            for (std::map<std::string, Jsonator>::const_iterator it = _object.begin(); it != _object.end(); ++it) {
                ret.push(it->second);
            }
        }
        return ret;
    }

    /**
     * @brief get json to vector
     *
     * @tparam T
     */
    template<typename T>
    operator std::vector<T>() const {
        std::vector<T> ret;
        if (_type == ARRAY) {
            for (std::size_t i = 0; i < _array.size(); ++i) {
                ret.push_back(_array[i]);
            }
        }
        else if (_type == OBJECT) {
            for (std::map<std::string, Jsonator>::const_iterator it = _object.begin(); it != _object.end(); ++it) {
                ret.push_back(it->second);
            }
        }
        return ret;
    }

    /**
     * @brief get number to T
     *
     * @tparam T
     * @throw AccessException if json type is not a number
     */
    template<typename T>
    operator T() const {
        return getNumber();
    }

    /**
     * @brief open and parse @p filename
     *
     * @param filename
     * @param comment active for skip the comment at parse
     * @param additionalNext active for skip the additional ',' at parse
     * @return Jsonator object
     * @throw ParseException by json format
     */
    static Jsonator parseFile(const char* filename, bool comment = true, bool additionalNext = true);

    /**
     * @brief parse @p stream
     *
     * @param stream
     * @param comment active for skip the comment at parse
     * @param additionalNext active for skip the additional ',' at parse
     * @return Jsonator
     * @throw ParseException by json format
     */
    static Jsonator parseStream(std::istream& stream, bool comment = true, bool additionalNext = true) {
        return _parseStream(stream, std::string(), comment, additionalNext);
    }

    /**
     * @brief parse @p str
     *
     * @param str
     * @param comment active for skip the comment at parse
     * @param additionalNext active for skip the additional ',' at parse
     * @return Jsonator
     * @throw ParseException by json format
     */
    static Jsonator parseString(const std::string& str, bool comment = true, bool additionalNext = true) {
        std::istringstream iss(str);
        return parseStream(iss, comment, additionalNext);
    }

    /**
     * @brief parse @p data with @p size
     *
     * @param data
     * @param size
     * @param comment active for skip the comment at parse
     * @param additionalNext active for skip the additional ',' at parse
     * @return Jsonator
     * @throw ParseException by json format
     */
    static Jsonator parseData(const void* data, std::size_t size, bool comment = true, bool additionalNext = true) {
        return parseString(std::string(static_cast<const char*>(data), size), comment, additionalNext);
    }

    /**
     * @brief get name of file after used parseFile
     *
     * @return const std::string&
     */
    const std::string& getFilename() const {
        return _filename;
    }

  private:
    /**
     * @brief Construct a new Jsonator object
     *
     * @param parent
     * @param index
     */
    Jsonator(const Jsonator* parent, const std::size_t& index);

    /**
     * @brief Construct a new Jsonator object
     *
     * @param parent
     * @param key
     */
    Jsonator(const Jsonator* parent, const std::string& key);

    static Jsonator _parseStream(std::istream& stream, const std::string& filename, bool comment, bool additionalNext);

    void _replaceParent(Jsonator& json);
    void _replace(const Jsonator& json);

    const Jsonator* _parent;
    std::vector<Jsonator> _array;
    std::size_t _arrayIndex;
    std::map<std::string, Jsonator> _object;
    std::string _objectKey;
    std::string _string;
    double _number;
    bool _boolean;
    Type _type;
    std::string _filename;
};

} // namespace mblet

#endif // _MBLET_JSONATOR_H_
/**
 * jsonator.cpp
 *
 * Licensed under the MIT License <http://opensource.org/licenses/MIT>.
 * Copyright (c) 2022-2023 BLET Mickaël.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// #include "mblet/jsonator.h"

#include <cctype>  // ::isdigit, ::isspace
#include <cstdlib> // ::strtod
#include <cstring> // ::strncmp
#include <fstream> // std::ifstream
#include <iomanip> // std::setprecision
#include <limits>  // std::numeric_limits

namespace mblet {

inline Jsonator::Jsonator() :
    _parent(NULL),
    _array(std::vector<Jsonator>()),
    _arrayIndex(0),
    _object(),
    _objectKey(""),
    _string(""),
    _number(0),
    _boolean(false),
    _type(NONE),
    _filename("") {}

inline Jsonator::Jsonator(const Jsonator* parent, const std::size_t& index) :
    _parent(parent),
    _array(std::vector<Jsonator>()),
    _arrayIndex(index),
    _object(std::map<std::string, Jsonator>()),
    _objectKey(""),
    _string(""),
    _number(0),
    _boolean(false),
    _type(NONE),
    _filename("") {}

inline Jsonator::Jsonator(const Jsonator* parent, const std::string& key) :
    _parent(parent),
    _array(std::vector<Jsonator>()),
    _arrayIndex(0),
    _object(std::map<std::string, Jsonator>()),
    _objectKey(key),
    _string(""),
    _number(0),
    _boolean(false),
    _type(NONE),
    _filename("") {}

inline Jsonator::Jsonator(const Jsonator& rhs) :
    _parent(rhs._parent),
    _array(rhs._array),
    _arrayIndex(rhs._arrayIndex),
    _object(rhs._object),
    _objectKey(rhs._objectKey),
    _string(rhs._string),
    _number(rhs._number),
    _boolean(rhs._boolean),
    _type(rhs._type),
    _filename(rhs._filename) {
    _replaceParent(*this);
}

inline Jsonator::~Jsonator() {}

inline void Jsonator::operator=(const Jsonator& json) {
    if (_type != NONE) {
        throw AccessException(*this, "is not null");
    }
    _array = json._array;
    _object = json._object;
    _string = json._string;
    _number = json._number;
    _boolean = json._boolean;
    _type = json._type;
    _filename = json._filename;
    _replaceParent(*this);
}

inline Jsonator Jsonator::parseFile(const char* filename, bool comment, bool next) {
    std::ifstream fileStream(filename); // open file
    if (fileStream.is_open()) {
        Jsonator json = _parseStream(fileStream, filename, comment, next); // parse file
        fileStream.close();
        json._filename = filename;
        return json;
    }
    else {
        throw ParseException(filename, "Open file failed");
    }
}

static inline void s_newlineDump(std::ostream& oss, const Jsonator& json, std::size_t indent) {
    if (!json.empty() && indent != 0) {
        oss << '\n';
    }
}

static inline void s_indentDump(std::ostream& oss, const Jsonator& json, std::size_t indent, char indentCharacter,
                                std::size_t index) {
    if (!json.empty() && indent != 0) {
        oss << std::string(indent * index, indentCharacter);
    }
}

static inline void s_stringDump(std::ostream& oss, const std::string& str) {
    static const std::pair<char, std::string> pairChars[] = {
        std::pair<char, std::string>('\a', "\\a"),  // Alert (bell, alarm)
        std::pair<char, std::string>('\b', "\\b"),  // Backspace
        std::pair<char, std::string>('\f', "\\f"),  // Form feed (new page)
        std::pair<char, std::string>('\n', "\\n"),  // New-line
        std::pair<char, std::string>('\r', "\\r"),  // Carriage return
        std::pair<char, std::string>('\t', "\\t"),  // Horizontal tab
        std::pair<char, std::string>('\v', "\\v"),  // Vertical tab
        std::pair<char, std::string>('\'', "\\'"),  // Single quotation mark
        std::pair<char, std::string>('\"', "\\\""), // Double quotation mark
        std::pair<char, std::string>('\\', "\\\\")  // Backslash
    };
    static const std::map<char, std::string> escapeChar(pairChars, pairChars + sizeof(pairChars) / sizeof(*pairChars));

    oss << '"';
    for (std::size_t i = 0; i < str.size(); ++i) {
        std::map<char, std::string>::const_iterator cit = escapeChar.find(str[i]);
        if (cit != escapeChar.end()) {
            oss << cit->second;
        }
        else {
            oss << str[i];
        }
    }
    oss << '"';
}

static inline void s_typeDump(std::ostream& oss, const Jsonator& json, std::size_t indent, char indentCharacter,
                              std::size_t index = 0);

static inline void s_objectDump(std::ostream& oss, const Jsonator& json, std::size_t indent, char indentCharacter,
                                std::size_t index) {
    oss << '{';
    s_newlineDump(oss, json, indent);
    ++index;
    for (Jsonator::object_const_iterator cit = json.object_begin(); cit != json.object_end(); ++cit) {
        if (cit != json.object_begin()) {
            oss << ',';
            s_newlineDump(oss, json, indent);
        }
        s_indentDump(oss, json, indent, indentCharacter, index);
        s_stringDump(oss, cit->second.getKey()); // key
        oss << ':';
        if (indent != 0) {
            oss << ' ';
        }
        s_typeDump(oss, cit->second, indent, indentCharacter, index);
    }
    s_newlineDump(oss, json, indent);
    --index;
    s_indentDump(oss, json, indent, indentCharacter, index);
    oss << '}';
}

static inline void s_arrayDump(std::ostream& oss, const Jsonator& json, std::size_t indent, char indentCharacter,
                               std::size_t index) {
    oss << '[';
    s_newlineDump(oss, json, indent);
    ++index;
    for (std::size_t i = 0; i < json.size(); ++i) {
        if (i != 0) {
            oss << ',';
            s_newlineDump(oss, json, indent);
        }
        s_indentDump(oss, json, indent, indentCharacter, index);
        s_typeDump(oss, json[i], indent, indentCharacter, index);
    }
    s_newlineDump(oss, json, indent);
    --index;
    s_indentDump(oss, json, indent, indentCharacter, index);
    oss << ']';
}

void s_typeDump(std::ostream& oss, const Jsonator& json, std::size_t indent, char indentCharacter, std::size_t index) {
    switch (json.getType()) {
        case Jsonator::ARRAY:
            s_arrayDump(oss, json, indent, indentCharacter, index);
            break;
        case Jsonator::OBJECT:
            s_objectDump(oss, json, indent, indentCharacter, index);
            break;
        case Jsonator::STRING:
            s_stringDump(oss, json.getString());
            break;
        case Jsonator::NUMBER:
            oss << json.getNumber();
            break;
        case Jsonator::BOOLEAN:
            if (json.getBoolean()) {
                oss << "true";
            }
            else {
                oss << "false";
            }
            break;
        case Jsonator::NONE:
            oss << "null";
            break;
    }
}

inline std::string Jsonator::dump(std::size_t indent, char indentCharacter) const {
    std::ostringstream oss("");
    oss << std::setprecision(std::numeric_limits<double>::digits10 + 1);
    s_typeDump(oss, *this, indent, indentCharacter);
    return oss.str();
}

/*******************************************************************************
 * PRIVATE
 ******************************************************************************/

/**
 * @brief structure of info parser
 */
struct JsonatorParseInfo {
    JsonatorParseInfo(const std::string& filename_, bool additionnalNext_) :
        filename(filename_),
        additionalNext(additionnalNext_) {}
    ~JsonatorParseInfo() {}

    std::size_t line(std::size_t i) const {
        return indexToLine[i];
    }

    std::size_t column(std::size_t i) const {
        return i - lineToIndex[indexToLine[i] - 1] + 1;
    }

    std::size_t lastLine(std::size_t /*i*/) const {
        return indexToLine.back();
    }

    std::size_t lastColumn(std::size_t i) const {
        return i + 1 - lineToIndex[indexToLine.back() - 1];
    }

    const std::string& filename;
    bool additionalNext;
    std::vector<std::size_t> indexToLine;
    std::vector<std::size_t> lineToIndex;
};

static inline std::string s_replaceEscapeChar(const std::string& str) {
    static const std::pair<char, char> pairChars[] = {
        std::pair<char, char>('a', '\a'),  // Alert (bell, alarm)
        std::pair<char, char>('b', '\b'),  // Backspace
        std::pair<char, char>('f', '\f'),  // Form feed (new page)
        std::pair<char, char>('n', '\n'),  // New-line
        std::pair<char, char>('r', '\r'),  // Carriage return
        std::pair<char, char>('t', '\t'),  // Horizontal tab
        std::pair<char, char>('v', '\v'),  // Vertical tab
        std::pair<char, char>('\'', '\''), // Single quotation mark
        std::pair<char, char>('"', '\"'),  // Double quotation mark
        std::pair<char, char>('\\', '\\')  // Backslash
    };
    static const std::map<char, char> escapeChar(pairChars, pairChars + sizeof(pairChars) / sizeof(*pairChars));
    std::string ret(str);
    for (std::size_t i = 0; i < ret.size(); ++i) {
        if (ret[i] == '\\') {
            const std::map<char, char>::const_iterator cit = escapeChar.find(ret[i + 1]);
            if (cit != escapeChar.end()) {
                ret.erase(i, 1);
                ret[i] = cit->second;
            }
        }
    }
    return ret;
}

static inline void s_stringJumpSpace(const std::string& str, std::size_t& index) {
    while (::isspace(str[index])) {
        ++index;
    }
}

static inline void s_parseNull(std::size_t& i, Jsonator& json) {
    json.newNull();
    i += sizeof("null") - 1;
}

static inline void s_parseBool(bool boolean, std::size_t& i, Jsonator& json) {
    json.newBoolean(boolean);
    if (boolean) {
        i += sizeof("true") - 1;
    }
    else {
        i += sizeof("false") - 1;
    }
}

static inline void s_parseNumber(const JsonatorParseInfo& info, const std::string& str, std::size_t& i,
                                 Jsonator& json) {
    if (str[i] == '0' && ::isdigit(str[i + 1])) {
        throw Jsonator::ParseException(info.filename, info.line(i), info.column(i), "Octal number not allowed");
    }
    char* ret = NULL;
    double number = ::strtod(str.c_str() + i, &ret);
    json.newNumber(number);
    std::size_t jump = ret - (str.c_str() + i);
    if (jump == 0) {
        throw Jsonator::ParseException(info.filename, info.line(i), info.column(i), "Bad number");
    }
    i += jump;
}

static inline void s_parseString(const JsonatorParseInfo& info, const std::string& str, std::size_t& i,
                                 Jsonator& json) {
    ++i; // jump '"'
    std::size_t start = i;
    // search end quote
    while (str[i] != '"') {
        if (str[i] == '\\' && (str[i + 1] == '"' || str[i + 1] == '\\')) {
            ++i;
        }
        else if (str[i] == '\0') {
            throw Jsonator::ParseException(info.filename, info.lastLine(i), info.lastColumn(i), "End of string");
        }
        else if (str[i] == '\n') {
            throw Jsonator::ParseException(info.filename, info.line(start), info.column(start), "New line in string");
        }
        ++i;
    }
    std::size_t end = i;
    ++i; // jump '"'
    json.newString(s_replaceEscapeChar(str.substr(start, end - start)));
}

static inline Jsonator& s_createNewObjectElement(const JsonatorParseInfo& info, const std::string& str, std::size_t& i,
                                                 Jsonator& json) {
    // parser key
    ++i; // jump '"'
    std::size_t start = i;
    // search end quote
    while (str[i] != '"') {
        if (str[i] == '\\' && (str[i + 1] == '"' || str[i + 1] == '\\')) {
            ++i;
        }
        else if (str[i] == '\0') {
            throw Jsonator::ParseException(info.filename, info.lastLine(i), info.lastColumn(i), "End of key");
        }
        else if (str[i] == '\n') {
            throw Jsonator::ParseException(info.filename, info.line(start), info.column(start), "New line in key");
        }
        ++i;
    }
    std::size_t end = i;
    ++i; // jump '"'
    s_stringJumpSpace(str, i);
    if (str[i] != ':') {
        throw Jsonator::ParseException(info.filename, info.line(i), info.column(i), "Need definition of object");
    }
    ++i; // jump ':'
    s_stringJumpSpace(str, i);
    // get key
    std::string key = s_replaceEscapeChar(str.substr(start, end - start));
    if (json.find(key) != json.object_end()) {
        throw Jsonator::ParseException(info.filename, info.line(start), info.column(start), "Key already exist");
    }
    return json[key];
}

static inline Jsonator& s_createNewArrayElement(Jsonator& json) {
    return json[json.size()];
}

static inline bool s_parseType(const JsonatorParseInfo& info, const std::string& str, std::size_t& i, Jsonator& json);

static inline void s_parseArray(const JsonatorParseInfo& info, const std::string& str, std::size_t& i, Jsonator& json) {
    json.newArray();
    bool next = false;

    ++i; // jump '['
    s_stringJumpSpace(str, i);
    while (str[i] != ']' || (next == true && info.additionalNext == false)) {
        if (str[i] == '\0') {
            throw Jsonator::ParseException(info.filename, info.lastLine(i), info.lastColumn(i),
                                           "End of array not found");
        }
        // search array, object, string, number, bool or null
        if (!s_parseType(info, str, i, s_createNewArrayElement(json))) {
            throw Jsonator::ParseException(info.filename, info.line(i), info.column(i), "Bad element of array");
        }
        s_stringJumpSpace(str, i);
        // next
        if (str[i] == ',') {
            ++i; // jump ','
            next = true;
            s_stringJumpSpace(str, i);
        }
        else {
            next = false;
        }
    }
    ++i; // jump ']'
}

static inline void s_parseObject(const JsonatorParseInfo& info, const std::string& str, std::size_t& i,
                                 Jsonator& json) {
    json.newObject();
    bool next = false;

    ++i; // jump '{'
    s_stringJumpSpace(str, i);
    while (str[i] != '}' || (next == true && info.additionalNext == false)) {
        if (str[i] == '\0') {
            throw Jsonator::ParseException(info.filename, info.lastLine(i), info.lastColumn(i),
                                           "End of object not found");
        }
        else if (str[i] == '"') {
            // search array, object, string, number, bool or null
            if (!s_parseType(info, str, i, s_createNewObjectElement(info, str, i, json))) {
                throw Jsonator::ParseException(info.filename, info.line(i), info.column(i), "Bad element in the key");
            }
        }
        else {
            throw Jsonator::ParseException(info.filename, info.line(i), info.column(i), "Key of object not found");
        }
        s_stringJumpSpace(str, i);
        // next
        if (str[i] == ',') {
            ++i; // jump ','
            next = true;
            s_stringJumpSpace(str, i);
        }
        else {
            next = false;
        }
    }
    ++i; // jump '}'
}

inline bool s_parseType(const JsonatorParseInfo& info, const std::string& str, std::size_t& i, Jsonator& json) {
    switch (str[i]) {
        case '[':
            s_parseArray(info, str, i, json);
            break;
        case '{':
            s_parseObject(info, str, i, json);
            break;
        case '"':
            s_parseString(info, str, i, json);
            break;
        case '-':
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
            s_parseNumber(info, str, i, json);
            break;
        case 't':
            if (!::strncmp(str.c_str() + i, "true", sizeof("true") - 1)) {
                s_parseBool(true, i, json);
            }
            else {
                return false;
            }
            break;
        case 'f':
            if (!::strncmp(str.c_str() + i, "false", sizeof("false") - 1)) {
                s_parseBool(false, i, json);
            }
            else {
                return false;
            }
            break;
        case 'n':
            if (!::strncmp(str.c_str() + i, "null", sizeof("null") - 1)) {
                s_parseNull(i, json);
            }
            else {
                return false;
            }
            break;
        default:
            return false;
            break;
    }
    return true;
}

static inline void s_replaceCommentBySpace(std::string& str) {
    for (std::size_t i = 0; i < str.size() && str[i] != '\0'; ++i) {
        if (str[i] == '"') {
            ++i;
            while (str[i] != '"') {
                if (str[i] == '\\' && (str[i + 1] == '"' || str[i + 1] == '\\')) {
                    ++i; // escape character
                }
                if (str[i] == '\n' || str[i] == '\0') {
                    break;
                }
                ++i;
            }
        }
        else if (str[i] == '/' && str[i + 1] == '*') {
            str[i] = ' '; // replace '/'
            ++i;
            str[i] = ' '; // replace '*'
            ++i;
            while (str[i] != '\0' && (str[i] != '*' || str[i + 1] != '/')) {
                str[i] = ' ';
                ++i;
            }
            if (str[i] != '\0') {
                str[i] = ' '; // replace '*'
                ++i;
                str[i] = ' '; // replace '/'
            }
        }
        else if (str[i] == '/' && str[i + 1] == '/') {
            str[i] = ' ';
            ++i;
            str[i] = ' ';
            ++i;
            while (str[i] != '\0' && str[i] != '\n') {
                str[i] = ' ';
                ++i;
            }
        }
    }
}

static inline std::string s_streamToStr(JsonatorParseInfo& info, std::istream& stream) {
    // generate line and column index
    std::ostringstream oss("");
    std::string line("");
    std::size_t nLine = 1;
    info.lineToIndex.push_back(0);
    while (std::getline(stream, line)) {
        if (nLine > 1) {
            oss << '\n';
        }
        oss << line;
        info.lineToIndex.push_back(line.size() + 1 + info.lineToIndex.back());
        info.indexToLine.insert(info.indexToLine.end(), line.size() + 1, nLine);
        ++nLine;
    }
    return oss.str();
}

inline Jsonator Jsonator::_parseStream(std::istream& stream, const std::string& filename, bool comment,
                                       bool additionalNext) {
    JsonatorParseInfo info(filename, additionalNext);
    std::string str = s_streamToStr(info, stream);
    if (comment) {
        s_replaceCommentBySpace(str);
    }
    std::size_t i = 0;
    s_stringJumpSpace(str, i);
    try {
        Jsonator json;
        switch (str[i]) {
            case '{':
                s_parseObject(info, str, i, json);
                s_stringJumpSpace(str, i);
                break;
            case '[':
                s_parseArray(info, str, i, json);
                s_stringJumpSpace(str, i);
                break;
            case '\0':
                return json;
            default:
                throw ParseException(info.filename, info.line(i), info.column(i), "Not a valid start character");
        }
        if (str[i] != '\0') {
            throw ParseException(info.filename, info.line(i), info.column(i), "Not a valid end character");
        }
        return json;
    }
    catch (const ParseException& /*e*/) {
        throw;
    }
}

inline void Jsonator::_replaceParent(Jsonator& json) {
    for (std::size_t i = 0; i < json._array.size(); ++i) {
        json._array[i]._parent = &json;
        _replaceParent(json._array[i]);
    }
    for (std::map<std::string, Jsonator>::iterator it = json._object.begin(); it != json._object.end(); ++it) {
        it->second._parent = &json;
        _replaceParent(it->second);
    }
}

inline void Jsonator::_replace(const Jsonator& json) {
    _array = json._array;
    _arrayIndex = json._arrayIndex;
    _object = json._object;
    _objectKey = json._objectKey;
    _string = json._string;
    _number = json._number;
    _boolean = json._boolean;
    _type = json._type;
    _filename = json._filename;
    _replaceParent(*this);
}

} // namespace mblet

#endif // #ifndef _AMALGAMATE_GUARD__SINGLE_INCLUDE_MBLET_JSONATOR_H_